### ISSUE TITLE
Blank screen on startup

### ISSUE THREAD

**Issue by xvxx** [ThomasTheSpaceFox/Zoxenpher#9]
This looks amazing, kudos.

When I try to run it on macOS Catalina I get a blank GUI window:

![image](https://user-images.githubusercontent.com/41523880/75476569-aee8c400-594f-11ea-8ef9-8ba4a1d3b574.png)

This is the console output:

````
$ python3 zoxenpher.py                                                                                         
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
libgop gopher library v0.2
check python version...
python 3
Libzox: loading configuration data.
Start MPE...
Zoxenpher Media Playback Engine initialized.
Zoxenpher v3.0.0.indev
Strazoloid Window Manager v1.4.0
````

Am I missing a dependency? Or maybe is macOS not supported?

**Comment by ThomasTheSpaceFox** [comment]
hmm... well, Zoxenpher has only ever been tested on Linux but there shouldn't be any issue with MacOS as its unix-based... odd... I honestly have no idea why that is happening...

hmm... is its CPU usage maxed out?
Also, try doing a Ctrl+c in the console, It might be stuck someplace...

**Comment by ThomasTheSpaceFox** [comment]
Im almost curious if the desktop class is active, and StrazoloidWM just isn't rendering for some reason... try Pressing Ctrl+Q and then Y and see if the window closes.

**Comment by ThomasTheSpaceFox** [comment]
If its not an issue with strazoloid, then the demo project (stz-test.py) in the [Strazoloid Repository](https://github.com/ThomasTheSpaceFox/Strazoloid-windowing-framework) should work fine.

Try downloading that repo and check stz-test.py's console output. I should be able to tell whether its stuck someplace, or just a rendering issue.

**Comment by xvxx** [comment]
Yes the CPU usage is 100%. This is what I get when I `ctrl-c`:

````
Strazoloid Window Manager v1.4.0
^CTraceback (most recent call last):
  File "zoxenpher.py", line 57, in <module>
    framesc.process()
  File "/Users/xvxx/Code/Zoxenpher/libzoxphr/strazoloidwm.py", line 851, in process
    pygame.display.flip()
KeyboardInterrupt
````

In the blank app, pressing "Ctrl+Q and then Y" does close the window:

```
shutting down...
Stopping MPE...
done.
```

I can't get stz-test.py in that repo to run, do I need a specific version of Python?

````
$ python3 stz-test.py                                                                     ~/Co/Strazoloid-windowing-framework:master
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Test desktop 1 stat 1: init call
Strazoloid Window Manager v1.4.0
GHOST TASK 1 stat 1: init call
test --REALLYLONGNAME--  -- ----------- stat 1: init call
Traceback (most recent call last):
  File "stz-test.py", line 118, in <module>
    testframe2=stz.framex(200, 100, "test2", pumpcall=event_test, xpos=None, ypos=None)
  File "/Users/xvxx/Code/Strazoloid-windowing-framework/strazoloidwm.py", line 160, in __init__
    if self.ypos<miny:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by ThomasTheSpaceFox** [comment]
the latter seems just a minor oversight... I should be able to fix that in a few minutes...

**Comment by ThomasTheSpaceFox** [comment]
Ok, check the new commit in the Strazoloid repository. Shouldn't crash this time...

**Comment by ThomasTheSpaceFox** [comment]
ok, heres a thought: It may be a bug in your version of pygame, related to resizable windows... if thats the case, i should be able to create a temporary "fix" by adding a config setting to enable/disable the resizable flag for the desktop...

**Comment by xvxx** [comment]
Okay yeah, the demo app runs now but it's the same blank screen:

![image](https://user-images.githubusercontent.com/41523880/75481778-73062c80-5958-11ea-8c58-945530e83999.png)

>  It may be a bug in your version of pygame

Which version do you use? I can try to install it. I'm on 1.9.6 which I just got with `pip3`.

**Comment by ThomasTheSpaceFox** [comment]
Ok, try this: download Zoxenpher's latest commit, then inside the zoxenpher directory, within ./usr/ inside the repo, create a file called cnf.dat

inside put this line:
```
resizable=False
```
Then run zoxenpher.py

**Comment by xvxx** [comment]
Same issue, though the window is no longer resizable:

![image](https://user-images.githubusercontent.com/41523880/75483250-50c1de00-595b-11ea-94b6-f2d6dcffc830.png)

**Comment by ThomasTheSpaceFox** [comment]
well... Sorry to say but there's not much else for me to try as i don't have access to a MacOS system... You might check if there's an upstream bug with your version of pygame... But sadly that's all i can suggest at this point... Closing issue for now.

**Comment by xvxx** [comment]
I upgraded pygame to 2.0.0.dev6 and it worked:

![image](https://user-images.githubusercontent.com/41523880/75484264-486aa280-595d-11ea-932e-e00d4e1c4ecf.png)

It's glorious. Finally a Gopher client that feels appropriate. Thank you!

**Comment by ThomasTheSpaceFox** [comment]
Id recommend re-enabling the resizable setting, also, do check the configuration help for setting everything up. it has a rundown of the various cnf.dat options. Thanks again for trying Zoxenpher!. :)

**Comment by ThomasTheSpaceFox** [comment]
Id definitely recommend seeing part 6 of configuration help for setting up the font with a monospace font, should you find ascii art fails to display correctly.

**Comment by xvxx** [comment]
Perfect thank you! The ASCII art looks great!
